# Use the base image with PHP 8.2 and Apache
FROM php:8.2-apache

# Set the working directory inside the container
WORKDIR /var/www/html

# Install system dependencies and PHP extensions
RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    zip \
    unzip && \
    docker-php-ext-configure gd --with-jpeg && \
    docker-php-ext-install gd pdo pdo_mysql
# Change the Apache document root to the current working directory
RUN sed -i -e 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/*.conf

RUN sed -i -e 's|/var/www/html|/var/www/html/public|g' /etc/apache2/apache2.conf  /etc/apache2/conf-available/*.conf
# Enable mod_rewrite for Laravel's URL rewriting
RUN a2enmod rewrite

# Copy the Laravel application files to the container
COPY . .

# Set permissions for Laravel to write to storage and bootstrap cache
RUN chown -R www-data:www-data storage bootstrap/cache


# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Laravel dependencies
RUN composer install && \
    cp .env.example .env && \
    php artisan key:generate

# Expose port 80 for Apache
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]

                            
